version: "3.9"
services:
  myblog:
    build: ./
    container_name: ar-navigation-fe_c
    ports:
      - '3000:3000'
    volumes:
      - ./public:/app/public
      - ./src:/app/src
    stdin_open: true
    tty: true
